//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     GenAPI Version: 7.0.8.6004
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Avalonia.Headless
{
    public static partial class AvaloniaHeadlessPlatform
    {
        public static void ForceRenderTimerTick(int count = 1) { }
    }
    public static partial class AvaloniaHeadlessPlatformExtensions
    {
        public static Avalonia.AppBuilder UseHeadless(this Avalonia.AppBuilder builder, Avalonia.Headless.AvaloniaHeadlessPlatformOptions opts) { throw null; }
    }
    public partial class AvaloniaHeadlessPlatformOptions
    {
        public AvaloniaHeadlessPlatformOptions() { }
        public bool UseCompositor { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
        public bool UseHeadlessDrawing { [System.Runtime.CompilerServices.CompilerGeneratedAttribute] get { throw null; } [System.Runtime.CompilerServices.CompilerGeneratedAttribute] set { } }
    }
    public partial interface IHeadlessWindow
    {
        Avalonia.Utilities.IRef<Avalonia.Platform.IWriteableBitmapImpl> GetLastRenderedFrame();
        void KeyPress(Avalonia.Input.Key key, Avalonia.Input.RawInputModifiers modifiers);
        void KeyRelease(Avalonia.Input.Key key, Avalonia.Input.RawInputModifiers modifiers);
        void MouseDown(Avalonia.Point point, int button, Avalonia.Input.RawInputModifiers modifiers = Avalonia.Input.RawInputModifiers.None);
        void MouseMove(Avalonia.Point point, Avalonia.Input.RawInputModifiers modifiers = Avalonia.Input.RawInputModifiers.None);
        void MouseUp(Avalonia.Point point, int button, Avalonia.Input.RawInputModifiers modifiers = Avalonia.Input.RawInputModifiers.None);
    }
}
