//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     GenAPI Version: 7.0.8.6004
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Avalonia.Browser.Blazor
{
    public partial class AvaloniaView : Microsoft.AspNetCore.Components.ComponentBase
    {
        public AvaloniaView() { }
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder builder) { }
        protected override System.Threading.Tasks.Task OnInitializedAsync() { throw null; }
    }
    public static partial class WebAppBuilder
    {
        public static Avalonia.AppBuilder Configure<TApp>() where TApp : Avalonia.Application, new() { throw null; }
        public static Avalonia.AppBuilder SetupWithSingleViewLifetime(this Avalonia.AppBuilder builder) { throw null; }
        public static Avalonia.AppBuilder UseBlazor(this Avalonia.AppBuilder builder) { throw null; }
    }
}
